name: Deploy to GitHub Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: dapp/yarn.lock

            - name: Install dependencies
              run: |
                  cd dapp
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  cd dapp
                  # Create .env file with necessary environment variables
                  echo "VITE_PUBLIC_URL=https://dev1line.github.io/nft-factory" > .env
                  echo "VITE_REACT_APP_TITLE=NFT Factory" >> .env
                  GH_PAGES=true yarn build

            - name: Add .nojekyll and verify files
              run: |
                  touch dapp/dist/.nojekyll
                  echo "Verifying important files exist:"
                  ls -la dapp/dist/
                  echo "Checking tonconnect-manifest.json:"
                  cat dapp/dist/tonconnect-manifest.json
                  echo "Checking .nojekyll:"
                  ls -la dapp/dist/.nojekyll

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dapp/dist
                  force_orphan: true
                  enable_jekyll: false
                  cname: false
