name: Deploy to GitHub Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: dapp/yarn.lock

            - name: Install dependencies
              run: |
                  cd dapp
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  cd dapp
                  GH_PAGES=true yarn build
                  
            - name: Prepare for deployment
              run: |
                  # Copy .nojekyll to disable Jekyll processing
                  cp .nojekyll dapp/dist/
                  # Verify the file was copied
                  ls -la dapp/dist/.nojekyll

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dapp/dist
                  force_orphan: true
                  enable_jekyll: false
